import Amy from "../../../images/team/Sales/Amy.jpg";
import Angela from "../../../images/team/Sales/Angela.jpg";
import Beth from "../../../images/team/Sales/Beth.jpg";
import Danny from "../../../images/team/Sales/Danny.jpg";
import Jenna from "../../../images/team/Sales/Jenna.jpg";
import Jennifer from "../../../images/team/Sales/Jennifer.jpg";
import Karyn from "../../../images/team/Sales/Karyn.jpg";
import Katie from "../../../images/team/Sales/Katie.jpg";
import Kat from "../../../images/team/Sales/Kat.jpg";
import Lindsay from "../../../images/team/Sales/Lindsay.jpg";
import Lisa from "../../../images/team/Sales/Lisa.jpg";
import Brittani from "../../../images/team/Sales/Brittani Michela.png";
import Nicole from "../../../images/team/Sales/Nicole.jpg";
import Renee from "../../../images/team/Sales/Renee.jpg";
import Sara from "../../../images/team/Sales/Sara.jpg";
import Shannon from "../../../images/team/Sales/Shannon.jpg";
import Stefanie from "../../../images/team/Sales/Stefani.jpg";
import Cindy from "../../../images/team/Sales/Cindy.jpg";
import Oksana from "../../../images/team/Sales/Oksana.jpg";
import Josella from "../../../images/team/Sales/Josella.jpg";
import Roger from "../../../images/team/Operations/Roger.jpg";
import Michelle from "../../../images/team/Sales/Michelle.jpg";
import Alexandra from "../../../images/team/Sales/Alexandra.jpg";
import Julie from "../../../images/team/Operations/Julie.jpg";
import Ricky from "../../../images/team/ECom/Ricky.jpg";
import Kaley from "../../../images/team/ECom/Kaley.jpg";
import Jen from "../../../images/team/Operations/Jen.jpg";
import Ethan from "../../../images/team/ECom/Ethan.jpg";
import Brittany from "../../../images/team/ECom/Brittany.jpg";
import Dean from "../../../images/team/ECom/Dean.jpg";
import Katelynn from "../../../images/team/ECom/Katelynn.jpg";
import NicoleV from "../../../images/team/ECom/Nicole.jpg";
import Gabrielle from "../../../images/team/ECom/Gabrielle.jpg";
import Sarah from "../../../images/team/ECom/Sarah.jpg";
import Steven from "../../../images/team/ECom/Steven.jpg";
import Will from "../../../images/team/ECom/Will.jpg";
import Jessica from "../../../images/team/Sales/Jessica Volstad.png";
import Kristina from "../../../images/team/ECom/Kristina.jpg";
import SarahC from "../../../images/team/ECom/SarahC.jpg";
import Melissa from "../../../images/team/ECom/Melissa.jpg";
import Mallory from "../../../images/team/Sales/Mallory.jpg";
import NicoleS from "../../../images/team/Sales/Nicole.jpg";
import Megan from "../../../images/team/Sales/Megan.jpg";
import Rory from "../../../images/team/Sales/Rory Tucker.png";
import ShannonL from "../../../images/team/Sales/ShannonL.jpg";
import Kailee from "../../../images/team/Sales/Kailee Murphy.png";
import SaraM from "../../../images/team/Sales/Sara_Moll.jpg";
import Erin from "../../../images/team/Sales/Erin_Boudreau.jpg";
import Jamie from "../../../images/team/Sales/Jamie Billings.jpg";
import SarahL from "../../../images/team/Sales/Sarah Lasam.jpg";
import Sean from "../../../images/team/Sales/Sean Stevens.jpg";
import Carolyn from "../../../images/team/Sales/Headshot_Crop_Carolyn_Topps.jpg";
import Katarina from "../../../images/team/Sales/Headshot_Crop_Katarina_Petronijevic.jpg";
import Lauren from "../../../images/team/Sales/Headshot_Crop_Lauren_LeMay.jpg";
import Lynette from "../../../images/team/Sales/Headshot_Crop_Lynette_Stwertnik.jpg";
import MichelleF from "../../../images/team/Sales/Headshot_Crop_Michelle_Fisher.jpg";
import MeganK from "../../../images/team/Sales/MeganKragenbrink.jpg";
import Chris from "../../../images/team/Operations/Chris.jpg";
import Cassie from "../../../images/team/Sales/Cassie Sackett.png";
import Hal from "../../../images/team/Sales/Hal Narotzky.png";
import Jocelyn from "../../../images/team/Sales/Jocelyn Cash.png";
import KatieG from "../../../images/team/Sales/Katie Greider.png";
import Melanie from "../../../images/team/Sales/Melanie Vess.png";
import RachelD from "../../../images/team/Sales/Rachel Dudek.png";
import Shelly from "../../../images/team/Sales/Shelly Aberson.png";
import StephanieK from "../../../images/team/Sales/Stephanie Kerkovich.png";
import TiffanyC from "../../../images/team/Sales/Tiffany Cobwell.png";
import Tom from "../../../images/team/Sales/Tom Pfeifer.png";
import Zac from "../../../images/team/Sales/Zac Moody.png";
import Amanda from "../../../images/team/Sales/AmandaE.png";
import LuisP from "../../../images/team/Sales/LuisP.jpg";
import Nolan from "../../../images/team/Sales/NolanE.jpg";
import AmandaG from "../../../images/team/Sales/Amanda Grimes.png";
import MariaAnn from "../../../images/team/Sales/MariaAnn.png";

//These are the default photos to be used when photo no avail.
import Male1 from "../../../images/team/Male1.jpg";
import Male2 from "../../../images/team/Male2.jpg";
import Female1 from "../../../images/team/Female1.jpg";
import Female2 from "../../../images/team/Female2.jpg";

export const People = {
  Amy: {
    name: "Amy Wagner",
    title: "Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Amy,
  },
  Angela: {
    name: "Angela Shimenetto",
    title: "Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Angela,
  },
  Beth: {
    name: "Beth Becker",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Beth,
  },
  Danny: {
    name: "Danny Hazan",
    title: "Account Coordinator",
    bio: "Danny joined Overture after 8 years as a journalist covering sports and music. He resides in Evanston.",
    movie: "Fargo",
    vacation: "Jackson Hole",
    why: "There weren’t enough Hazan’s",
    image: Danny,
  },
  Jenna: {
    name: "Jenna Herchenbach",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Jenna,
  },
  Jennifer: {
    name: "Jennifer Schafer",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Jennifer,
  },
  Karyn: {
    name: "Karyn Augelli",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Karyn,
  },
  Katie: {
    name: "Katie Puente",
    title: "Account Coordinator",
    bio: "",
    movie: "The Man Who Knew Too Little",
    vacation: "Mexico",
    why: "The job description included a preferred (but not required) “a love for The Office and Chipotle burritos”. I knew I could get along with these people.",
    image: Katie,
  },
  Kat: {
    name: "Kat Heer",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Kat,
  },
  Lindsay: {
    name: "Lindsay Oswalt",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Lindsay,
  },
  Lisa: {
    name: "Lisa Sparreo",
    title: "Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Lisa,
  },
  Brittani: {
    name: "Brittani Michela",
    title: "Sr. Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Brittani,
  },
  Nicole: {
    name: "Nicole Jones",
    title: "National Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Nicole,
  },
  Renee: {
    name: "Renee Kutrubis",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Renee,
  },
  Sara: {
    name: "Sara Dell",
    title: "Project Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Sara,
  },
  Shannon: {
    name: "Shannon DeCaluwe",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Shannon,
  },
  Stefanie: {
    name: "Stefanie Lenzi",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Stefanie,
  },
  Cindy: {
    name: "Cindy Waters",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Cindy,
  },
  Oksana: {
    name: "Oksana Tupikov",
    title: "Sales Admin",
    bio: "",
    movie:
      "If Oksana was stranded on a deserted island, the three items she would take with her are a metal firestarter, a book about plants, and a German Shepard.",
    vacation: "If she could be any animal in the world, she would be a falcon.",
    why: "A job she would be terrible at is a truck driver.",
    image: Oksana,
  },
  Josella: {
    name: "Josella Boudreau",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Josella,
  },
  Roger: {
    name: "Roger Brual",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Roger,
  },
  Michelle: {
    name: "Michelle Inman",
    title: "Sales Account Admin",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Michelle,
  },
  Alexandra: {
    name: "Alexandra Ladd",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Alexandra,
  },
  Julie: {
    name: "Julie Maldonado",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Julie,
  },
  Ricky: {
    name: "Ricky Bryant",
    title: "Project Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Ricky,
  },
  Kaley: {
    name: "Kaley Sullivan",
    title: "Account Coordinator ",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Kaley,
  },
  Jen: {
    name: "Jen Powles",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Jen,
  },
  KatieD: {
    name: "Katie Dinning",
    title: "Sales Admin",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Female1,
  },
  SaraM: {
    name: "Sara Moll",
    title: "Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: SaraM,
  },
  Ethan: {
    name: "Ethan Collins",
    title: "Director of Sales",
    bio: "",
    movie: "Saving Private Ryan",
    vacation: "Reykjavik, Iceland",
    why: "Because creativity is the driving force behind Overture’s growth. From product design to logistical problem solving, this is a company that has fun innovating!",
    image: Ethan,
  },
  Brittany: {
    name: "Brittany Foley",
    title: "Sr. Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Brittany,
  },
  Dean: {
    name: "Dean Schwartz",
    title: "Sr. Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Dean,
  },
  Katelynn: {
    name: "Katelynn Fioretto",
    title: "Sr. Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Katelynn,
  },
  NicoleV: {
    name: "Nicole Vechiola",
    title: "Sr. Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: NicoleV,
  },

  Gabrielle: {
    name: "Gabby Whitmer",
    title: "Sr. Account Executive",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Gabrielle,
  },
  Sarah: {
    name: "Sarah Hoffmann",
    title: "Sr. Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Sarah,
  },
  Steven: {
    name: "Steven Missak",
    title: "Sr. Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Steven,
  },
  Will: {
    name: "Will Petlak",
    title: "Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Will,
  },
  Jessica: {
    name: "Jessica Volstad",
    title: "Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Jessica,
  },
  Kristina: {
    name: "Kristina Keller",
    title: "Sales Admin",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Kristina,
  },
  Kimberline: {
    name: "Kimberlin Sawyer",
    title: "Account Director",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Female1,
  },
  SarahC: {
    name: "Sarah Crowl",
    title: "Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: SarahC,
  },
  Melissa: {
    name: "Melissa Dysinger",
    title: "Account Development Specialist",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Melissa,
  },
  Mallory: {
    name: "Mallory Geniesse",
    title: "Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Mallory,
  },
  Rory: {
    name: "Rory Tucker",
    title: "Sr. Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Rory,
  },
  NicoleS: {
    name: "Nicole Sommerville",
    title: "Sr. Account Executive",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: NicoleS,
  },
  Megan: {
    name: "Megan Murphy",
    title: "Sr. Account Manager",
    bio: "",
    movie: "Homeward Bound (if you don’t love this movie you have no soul)",
    vacation: "MEXICO!! ",
    why: "Loved the idea of working for a woman owned company. Working for women, with women, as a woman, was right up my alley!",
    image: Megan,
  },
  Eric: {
    name: "Eric Yaggi",
    title: "Sr. Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Male1,
  },

  ShannonL: {
    name: "Shannon Lassiter",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: ShannonL,
  },
  Kailee: {
    name: "Kailee Murphy",
    title: "Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Kailee,
  },
  Katarina: {
    name: "Katarina Petronijevic",
    title: "Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Katarina,
  },
  Erin: {
    name: "Erin Boudreau",
    title: "Sales Account Admin",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Erin,
  },
  Lauren: {
    name: "Lauren LeMay",
    title: "Sales Account Executive",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Lauren,
  },
  MichelleF: {
    name: "Michelle Fisher",
    title: "Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: MichelleF,
  },
  KellyM: {
    name: "Kelly McNeff ",
    title: "Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Female2,
  },
  Taylor: {
    name: "Taylor Moore",
    title: "Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Female1,
  },
  Jamie: {
    name: "Jamie Billings",
    title: "Sales Account Admin",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Jamie,
  },
  SarahL: {
    name: "Sarah Lasam",
    title: "Account Manager, Inside Sales",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: SarahL,
  },
  Sean: {
    name: "Sean Stevens",
    title: "Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Sean,
  },
  Dennis: {
    name: "Dennis Gonzalez",
    title: "Sales Admin",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Male1,
  },
  Devon: {
    name: "Devon Huston",
    title: "Sales Account Admin",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Male2,
  },
  Carolyn: {
    name: "Carolyn Topps",
    title: "Sales Account Admin",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Carolyn,
  },
  Lynette: {
    name: "Lynette Stwertnik",
    title: "Sr Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Lynette,
  },
  Jocelyn: {
    name: "Jocelyn Cash",
    title: "Sales Account Admin",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Jocelyn,
  },
  Melanie: {
    name: "Melanie Vess",
    title: "Sales Account Admin",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Melanie,
  },
  Tom: {
    name: "Tom Pfeifer",
    title: "Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Tom,
  },
  Shelly: {
    name: "Shelly Aberson",
    title: "Sales Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Shelly,
  },
  Hal: {
    name: "Hal Narotzky",
    title: "Sales Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Hal,
  },
  MeganK: {
    name: "Megan Kragenbrink",
    title: "Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: MeganK,
  },
  ChrisM: {
    name: "Chris Mendoza",
    title: "Sales Admin",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Chris,
  },
  Cassie: {
    name: "Cassie Sackett",
    title: "Sr. Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Cassie,
  },
  AmyB: {
    name: "Amy Burger",
    title: "Sr. Account Executive",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Female2,
  },
  KatieG: {
    name: "Katie Greider",
    title: "Sr. Account Executive",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: KatieG,
  },
  Amanda: {
    name: "Amanda Emran",
    title: "Sales Account Admin",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Amanda,
  },
  Zac: {
    name: "Zac Moody",
    title: "Sr. Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Zac,
  },
  RachelD: {
    name: "Rachel Dudek",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: RachelD,
  },
  StephanieK: {
    name: "Stephanie Kerkovich",
    title: "Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: StephanieK,
  },
  TiffanyC: {
    name: "Tiffany Cobwell",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: TiffanyC,
  },
  LuisP: {
    name: "Luis Pacheco",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: LuisP,
  },
  AshleyL: {
    name: "Ashley Lewis",
    title: "Account Manager",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Female1,
  },
  Wendy: {
    name: "Wendy Coffey",
    title: "Account Director",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Female1,
  },
  Nolan: {
    name: "Nolan Elsing",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Nolan,
  },
  Tracy: {
    name: "Tracy Queen",
    title: "Sr. Account Executive",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Female1,
  },
  CindyD: {
    name: "Cindy Denton",
    title: "Sr. Account Executive",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Female1,
  },
  MariaAnn: {
    name: "MariaAnn Savitz-Davis",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: MariaAnn,
  },
  Tamia: {
    name: "Tamia Wheatley",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Female1,
  },
  MatthewC: {
    name: "Matthew Christoff",
    title: "Account Executive",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Male1,
  },
  LilianaN: {
    name: "Liliana Nunez",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: Male1,
  },
  AmandaG: {
    name: "Amanda Grimes",
    title: "Account Coordinator",
    bio: "",
    movie: "",
    vacation: "",
    why: "",
    image: AmandaG,
  },
};
