import Test from '../../images/team/ExpertsPhotos/test.png'

export const People = {
    JoG: {
        name: 'Jo Gilley',
        title: 'Chief Excutive Officer/Owner',
        bio: "Jo is one of the original investors in Overture. She brings 22 years of management, strategic planning and marketing experience to the team. She was previously the VP of marketing for Chicago’s WNBA team, the Sky; director of marketing at The Cradle, the Midwest’s largest adoption agency; and VP of marketing at Cognitive Concepts, an early literacy technology company. Jo helped build two successful Internet start-ups: as vice president of marketing at Tunes.com, Internet music hub and producer of RollingStone.com, and as director of corporate strategy at BackWeb Technologies, where she redefined the company’s positioning prior to a successful initial product launch and initiated European marketing programs in advance of market entry. She was the first communications director for IBM’s Software Group when it was formed as a $12 billion software “company,” and managed the worldwide launch of a major new software product with a series of Telly Award-winning launch events that generated broad, worldwide media coverage. Before starting her career in marketing, Jo Central Intelligence Agency. When she’s not working, she’s watching her sons' baseball games or reading. Favorite movie: I could never pick just one: The Natural, Avatar, Lord of the Rings, Field of Dreams, One Fine Day. Favorite vacation spot: Kiawah Island, Kauai, Venice, Paris — and all the places I haven’t been yet.",
        image: Test
    },
    RonG: {
        name: 'Ron Gilley',
        title: 'Chief Operating Officer',
        bio: 'Bacon ipsum dolor amet chuck alcatra pork chop sausage biltong burgdoggen. Kielbasa ham hock flank drumstick pork frankfurter t-bone. Tail pork loin kevin, pig pork chop buffalo beef tenderloin andouille bresaola doner. T-bone leberkas salami short ribs sirloin. Burgdoggen ground round landjaeger alcatra t-bone shankle ball tip pastrami drumstick porchetta turkey jerky. Tri-tip ground round turkey chuck, ball tip t-bone beef cupim biltong pastrami filet mignon. Kielbasa tongue cupim, turducken chicken salami short loin tri-tip alcatra capicola.'
    },
    TejS: {
        name: 'Tej Shah',
        title: 'VP, Marketing & E-Commerce',
        bio: "Tej brings a unique business minded skill-set and proven track record in marketing to Overture Promotions. Prior to joining Overture, Tej co-founded an internet company, WeRemember.org, which was featured in a handful of publications, including The Wall Street Journal and US News & World Report. His experience also consists of developing and implementing the marketing and e-commerce strategies for a variety of companies, including ServiceMaster, SharkZoo and Bank of America. Tej was previously nominated as one of BusinessWeek's Top 25 Entrepreneurs Under 25. Additionally, Tej is a guest speaker, writer and trainer on business and marketing strategy. Tej has a bachelor's degree in both business and pre-medical biochemistry from Loyola University Chicago. WHAT IS YOUR FAVORITE MOVIE? Superbad, Step Brothers, Bad Boys II, Gladiator, Remember the Titans, Rocky, Donnie Brasco, Bourne Identity... AHHHH!!! Too many to pick just one! WHAT IS YOUR FAVORITE VACATION SPOT? Anywhere with beer and a beach. WHY DID YOU CHOOSE OVERTURE PROMOTIONS? I joined Overture mainly because of the free bagels every morning and mandatory happy hour outings. But… I decided to stay with Overture because of what they have managed to achieve in the past ten years as well as where they are going in the future. Overture separates itself from its competitors by offering in house services that can't be found anywhere else, consistently investing in technology and most importantly, by truly offering creativity, concept and service to their clients rather than just products.",
    },
    MikeW: {
        name: 'Mike Wilson',
        title: 'VP, Operations',
        bio: 'Mike has shared his experience in management and growth in many departments within Overture. Assisting in all aspects of the building, from managing all in-house services to quality control for all items that are inventoried. No two days are the same in this building and that constant change is what continues to excel Mike forward. Mike understands in order to stay ahead of the curve, Overture needs to constantly be streamlining operations in our many e-commerce stores and finding new technology that will assist in the many decoration methods Overture offers. With all of Overture’s many in-house services, Mike enjoys working with the sales staff to find creative and innovative solutions to new challenges that arise. Mike has earned a bachelor’s degree from Purdue University. WHAT IS YOUR FAVORITE MOVIE?   Goonies. I might hold the world record for seeing this movie. WHAT IS YOUR FAVORITE VACATION SPOT? Paris and London. WHY DID YOU CHOOSE OVERTURE PROMOTIONS?Overture has brought together the best in the industry! Whether it be working with the sales staff or operations, every day is a collaborative effort that moves us forward. I have not seen another company that has so much to offer under one roof. This is a value for the customers that we service with our many in-house services and e-commerce solutions, and also to the employees that work in such a unique atmosphere. Once I walked through those doors on my first day, I knew I had found a company I wanted to be a part of and grow with.',
    }
}